#!/bin/sh
#
# makesrcdist - make a source distribution of msysmon.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating msysmon-$version.tar.gz...
git archive --format tar --prefix=msysmon-$version/ HEAD | gzip -v9 >msysmon-$version.tar.gz
gpg --detach-sign msysmon-$version.tar.gz
